name: Build
run-name: ${{ github.actor }} triggered a build
on:
  - workflow_dispatch
  - workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rebornos/rebornos:latest
      ports:
        - 80
      options: --privileged
    steps:
      - id: init_docker_step
        name: Initialize Docker Container        
        run: sh /usr/bin/init-rebornos-docker.sh
      - id: checkout_repository_step
        name: Checkout Git Repository
        uses: actions/checkout@v3
      - id: build_iso_step
        name: Build the ISO
        run: sh scripts/build.sh              
      - id: upload_iso_artifact_step
        name: Upload the ISO Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: built-iso
          path: output/rebornos*.iso


