name: Build
run-name: ${{ github.actor }} triggered a build
# on: 
#   workflow_call
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rebornos/rebornos:latest
      ports:
        - 80
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build the ISO
        run: |
          sh /usr/bin/init-rebornos-docker.sh \
          && sh scripts/build.sh
      - name: Upload the ISO artifact
        uses: actions/upload-artifact@v3
        with: 
          name: built-iso
          path: output/rebornos*.iso


