name: Build and Publish
run-name: ${{ github.actor }} triggered build and publish
on: 
  workflow_dispatch:
    inputs: 
      tag:
        description: Release Tag
        required: true
        type: string
        

