name: Build
run-name: ${{ github.actor }} triggered a build
# on: 
#   workflow_call
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rebornos/rebornos:latest
      ports:
        - 80
    steps:
      - name: init_docker_step
        run: sh /usr/bin/init-rebornos-docker.sh
      - name: checkout_repository_step
        uses: actions/checkout@v3
      - name: build_iso_step
        run: sh scripts/build.sh              
      - name: upload_iso_artifact_step
        uses: actions/upload-artifact@v3
        with: 
          name: built-iso
          path: output/rebornos*.iso


